name: Test with PyTest
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root --no-interaction --all-extras

      - name: Run tests
        run: |
          poetry run pytest -s --disable-warnings --cov-report=xml --cov-append --cov=mtproto tests

      - name: Print coverage report
        run: |
          poetry run coverage report

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
