name: Test with PyTest
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root --no-interaction --all-extras

      - name: Disable GIL on free-threaded Python builds
        run: |
          if [[ "${{ matrix.python-version }}" == "3.13t" || "${{ matrix.python-version }}" == "3.14t" ]]; then
            echo "PYTHON_GIL=0" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: |
          poetry run pytest -s --cov-report=xml --cov-append --cov=mtproto tests
        env:
          PYTHON_GIL: ${{ env.PYTHON_GIL }}

      - name: Print coverage report
        run: |
          poetry run coverage report

#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
